2a982533-cac1-4da2-89a8-5c713b2835b2:
  uuid: 2a982533-cac1-4da2-89a8-5c713b2835b2
  menu_name: main
  title: Shop
  parent: ''
  link:
    -
      uri: 'internal:/shop'
      title: ''
      options: {  }
  description: ''
  enabled: '1'
  expanded: '0'
  weight: '-49'
  langcode: en
ccfd5e0d-99f6-462b-a8a5-02df5d19d2e7:
  uuid: ccfd5e0d-99f6-462b-a8a5-02df5d19d2e7
  menu_name: main
  title: Stories
  parent: ''
  link:
    -
      uri: 'internal:/stories'
      title: ''
      options: {  }
  description: ''
  enabled: '1'
  expanded: '0'
  weight: '-48'
  langcode: en
aeeb4236-7b6b-4ff6-b0ce-40c0087a53cb:
  uuid: aeeb4236-7b6b-4ff6-b0ce-40c0087a53cb
  menu_name: main
  title: Collections
  parent: ''
  link:
    -
      uri: 'internal:/collections'
      title: ''
      options: {  }
  description: ''
  enabled: '1'
  expanded: '0'
  weight: '0'
  langcode: en
